language: go
go:
  - stable
  - "1.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"

go_import_path: go.elastic.co/apm

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - go: "1.x"

before_install:
  - go get -v golang.org/x/tools/cmd/goimports
  - if (go run scripts/mingoversion.go 1.10 &>/dev/null); then go get -v golang.org/x/lint/golint; fi

script:
  - make install check

jobs:
  include:
    - os: osx     
    - stage: coverage
      sudo: required
      services:
        - docker
      script:
        - scripts/docker-compose-testing up -d --build
        - scripts/docker-compose-testing run -T --rm go-agent-tests make coverage > coverage.txt
        - bash <(curl -s https://codecov.io/bash)
